name: flutter_sound_suite
description: a flutter sound suite for record and play voice easily, dependencies on dio 4.0.0, intl 0.17.0, uuid 3.0.4
  and so on
version: 2.0.0
homepage: https://github.com/SecretUltimate/flutter_sound_suite

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  intl: ^0.17.0
  uuid: ^3.0.4
  provider: ^5.0.0
  path_provider: ^2.0.2
  flutter_sound: ^8.1.4
  permission_handler: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/voice/volume_1.png
    - assets/voice/volume_2.png
    - assets/voice/volume_3.png
    - assets/voice/volume_4.png
    - assets/voice/volume_5.png
    - assets/voice/volume_6.png
    - assets/voice/volume_7.png
